### ISSUE TITLE
Add jsdoc task to Gruntfile

### ISSUE THREAD

**Issue by jrbarron** [Kinvey/js-library#1]
It would be great if Gruntfile.js contained a jsdoc task for generating the documentation.

**Comment by ThomasConner** [comment]
Hi @jrbarron. We update the documentation at [API Reference](http://devcenter.kinvey.com/nodejs/reference/api/index.html) with each release of the library. Are you wanting to be able to generate a local copy rather then use our website?

**Comment by jrbarron** [comment]
Hi @ThomasConner, it's been quite a while since I made this task and to be honest I can't remember what I wanted :confused:  I believe the reason I wanted to generate the docs locally was to bundle them in a doc package for Dash (https://kapeli.com/dash). I understand this is not a high priority though so I won't be offended if you just decide to close this issue :wink:

**Comment by ThomasConner** [comment]
Ok no problem. Sorry for the slow response. I use Dash as well and I think it would be great to bundle our docs in a package for Dash. I am going to go ahead an close this issue but I will make a ticket internally to circle back around on how we might be able to integrate our docs into Dash. Thanks for the recommendation.
