### ISSUE TITLE
Error, header missing in response in version 1.2.0

### ISSUE THREAD

**Issue by valentinpignolet** [Kinvey/js-library#4]
Hi, 

Since I use the latest version of kinvey I have the same issue each time I try to logout a user : 

"Content-Type header missing in response. Please add Content-Type header to response with value application/json",

I did not update my authentication code as it worked with kinvey 1.1.11.

What am i supposed to do ? 

Cheers

**Comment by ThomasConner** [comment]
Hey @valentinpignolet. Thanks for reporting the issue. We are working on a fix.

**Comment by ThomasConner** [comment]
Can you try updating to the latest release (version 1.2.1) and see if the issue goes away?
